### PR TITLE
add way to edit 'onset directly from edit-numbox

### PR DESCRIPTION
**Pull request by andersvi**
Adding direct editing of onset (in the numbox) for selected notes.  Only active if (= obj-mode "chord")

### CODE REVIEW

**Comment by j-bresson** [comment]
Sorry still buggy :)
Ex. open th eeditor, mode 'note' select a note, then select the 'onset' menu : onset is NIL but not disabled : drag it => crash

**Comment by andersvi** [comment]
I thought i got rid of that.  The exact same steps works here, ie. the onset
is grayed out and doesn't react to dragging.  Did you check with a new
(or re-evaluated) chord-seq after loading the patch?

**Comment by andersvi** [comment]
No sorry, it's me messing up my commit to this test branch... 2 seconds...

**Comment by j-bresson** [comment]
See : https://nubo.ircam.fr/index.php/s/oJRQqXN7ngDPsJH
(if you can read it?)

**Comment by andersvi** [comment]
Nice video!  Check with the latest push.

Nice (for me) to get more acquainted with these kinds of git based dev-tools as well.

**Comment by j-bresson** [comment]
All seems good with the last commit.

**Comment by andersvi** [comment]
Cool, i'll push to master then.

**Pull request merged**
